# From https://github.com/libyui/libyui/blob/master/.github/workflows/publish-api-doc.yml

# This generates Doxygen html documentation
# and pushes them to the "gh-pages" branch which publishes them to strangeQuark1041.github.io/samarium/index.html
#
# See also https://gist.github.com/shundhammer/ed359db0d9329d4db551528256060d2a
#
# GitHub actions syntax:
#   https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: docs

# Trigger this when a pull request is merged (which implies pushing to main).
on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Create clean gh-pages branch
      run:  git checkout -b gh-pages

    - name: Install Clang
      uses: egor-tensin/setup-clang@v1

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: "3.22.x"

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Install TBB
      run: sudo apt-get update && sudo apt-get install libtbb-dev

    - name: Check Tool Versions
      run: |
        conan    --version
        cmake    --version
        clang++  --version

    - name: Configure Conan
      run: |
        conan profile new default --detect

    - name: Generate docs
      run:  |
        cmake --preset=default
        cmake --build build --target docs

    - name: Copy docs to api directory
      run:  |
        rm ./*.md
        mkdir -p api
        cp -R ./build/docs/* .

    - name: Add generated docs to Git repo in the gh-pages branch
      run:  |
        git config --global user.email "jaibellare@gmail.com"
        git config --global user.name  "$GITHUB_WORKFLOW GitHub action"
        git add .
        git commit -am "Generated docs"

    - name: Publish autodocs as GitHub pages
      run:  git push -f origin gh-pages:gh-pages

    - name: Result URLs
      run:  |
        REPO_OWNER=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)
        REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)
        echo "Formatted API docs:  https://$REPO_OWNER.github.io/$REPO_NAME/api/"
        echo ""
        echo "GitHub pages branch: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/tree/gh-pages" 
