baseURL = 'https://strangequark1041.github.io/samarium/'
languageCode = 'en-us'
title = 'Samarium'
theme = 'terminal'

[params]
    # dir name of your main content (default is `content/posts`).
    # the list of set content will show up on your index page (baseurl).
    # contentTypeName = "posts"

    # ["orange", "blue", "red", "green", "pink"]
    themeColor = "blue"
    fullWidthTheme = true

[markup.goldmark.renderer]
    unsafe = true
