name: CMake Build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls -AlhR ${{ github.workspace }}
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 11
          platform: x64
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.22.x'
      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
      - name: Install other deps
        run: sudo apt-get install valgrind find
      - name: Check Tool Versions
        run: |
          conan    --version
          cmake    --version
          c++      --version
          valgrind --version
          find     --version

      - name: Setup Build Environment
        run: mkdir -p build
      - name: Install Conan dependencies
        working-directory: ./build
        run: |
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
          export CONAN_SYSREQUIRES_MODE=enabled
          conan install .. --build=missing
      - name: CMake
        working-directory: ./build
        run: cmake ..
      - name: CMake Build
        working-directory: ./build
        run: cmake --build .
      - name: CTest
        working-directory: ./build
        run: ctest
