name: Clang

on:
  push:
    branches: [main, gl]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 2 * * *" # run everyday to keep fresh

env:
  # Path to the CMake build directory.
  build: "${{ github.workspace }}/build"
  CONAN_SYSREQUIRES_MODE: "enabled"
  CONAN_USER_HOME: "${{ github.workspace }}/release/"

jobs:
  clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Clang
        uses: egor-tensin/setup-clang@v1

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1.12

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Check Tool Versions
        run: |
          printf "#include <ciso646>\nint main () {}" | clang -E -stdlib=libc++ -x c++ -dM - | grep _LIBCPP_VERSION
          printf "conan: $(conan    --version)\n\n"
          printf "cmake: $(cmake    --version)\n\n"
          printf "clang: $(clang++  --version)\n\n"
          printf "gcc:   $(g++  --version)\n\n"
          printf "clang: $(which clang++)\n\n"
          printf "gcc:   $(which g++)\n\n"
          printf "libc++:$(ldconfig -p | grep libc++)\n\n"
          printf "libstdc++:$(ldconfig -p | grep libstdc++)\n\n"

      - name: Configure Conan
        run: |
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan config set tools.system.package_manager:mode=install
          conan config get tools.system.package_manager
          conan profile update settings.compiler=clang default
          conan profile update settings.compiler.version=10 default

      - name: Cache .conan directory
        id: cache-conan
        uses: actions/cache@v3
        env:
          cache-name: cache-conan-modules
        with:
          path: ${{ env.CONAN_USER_HOME }}
          key: ${{ runner.os }}-builder-${{ env.cache-name }}-${{ hashFiles('**/conanfile.py') }}
          restore-keys: ${{ runner.os }}-builder-${{ env.cache-name }}-

      - name: Run Conan
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: conan install . -b missing -if build -pr:b=default -o samarium:build_tests=True -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True

      - name: Install mold
        uses: rui314/setup-mold@v1

      - name: CMake Configure
        run: cmake --preset=ci

      - name: CMake Build
        run: cmake --build --preset=default

      - name: CTest
        run: ctest --preset=default
