name: Clang

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 2 * * *" # run everyday to keep fresh

env:
  # Path to the CMake build directory.
  build: "${{ github.workspace }}/build"
  CONAN_SYSREQUIRES_MODE: "enabled"

jobs:
  clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Clang
        uses: egor-tensin/setup-clang@v1

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1.12

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Install TBB
        run: sudo apt-get update && sudo apt-get install libtbb-dev

      - name: Check Tool Versions
        run: |
          printf "#include <ciso646>\nint main () {}" | clang -E -stdlib=libc++ -x c++ -dM - | grep _LIBCPP_VERSION
          printf "conan: $(conan    --version)\n"
          printf "cmake: $(cmake    --version)\n"
          printf "clang: $(clang++  --version)\n"
          printf "gcc:   $(g++  --version)\n"
          printf "clang: $(which clang++)\n"
          printf "gcc:   $(which g++)\n"
          printf "libc++:$(ldconfig -p | grep libc++)\n"
          printf "libstdc++:$(ldconfig -p | grep libstdc++)\n"

      - name: Configure Conan
        run: |
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan config set tools.system.package_manager:mode=install
          conan config get tools.system.package_manager

      - name: CMake Configure
        run: |
          conan install . -b missing -if build -pr:b=default -o samarium:build_tests=True -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True
          cmake --preset=ci

      - name: CMake Build
        run: cmake --build --preset=default

      - name: CTest
        run: ctest --preset=default
